### ISSUE TITLE
native library missing

### ISSUE THREAD

**Issue by misaelriojasftf** [kaoz70/flutter_kushki#1]
Taking the token from directly from api is not that safe for production usage. 

do you think proper to have it implemented with own IOS/Android libraries ?

**Comment by kaoz70** [comment]
I reviewed the Java library when I created this and it does exactly the same thing, it doesn't do anything special. It passes on the token and communicates directly with the API

There are no security issues on the client side of the code. You can review Kishki's own Java library and see what I'm talking about.

Basically their library is an HTTP Client with methods that resolve to their endpoints.

The same as this one.
